spring:
  application:
    name: forum-service
  data:
    jdbc:
      dialect: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always

server:
  port: 8082

mySecretKey : MySuperSecretKeyForJWTsguguofterdfyulioluktydfyiuofdtrsdfuliguydsrtfuftrsesj


