spring:
  application:
    name: forum
  data:
    jdbc:
      dialect: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
#  cloud:
#    consul:
#      discovery:
#        register: true
#      host: ${CONSUL_HOST:localhost}
#      port: ${CONSUL_PORT:8500}

mySecretKey : MySuperSecretKeyForJWTsguguofterdfyulioluktydfyiuofdtrsdfuliguydsrtfuftrsesj


