spring:
  application:
    name: authentification
  data:
    jdbc:
      dialect: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
    loadbalancer:
      enabled: false

server:
  port: 8081


mySecretKey : MySuperSecretKeyForJWTsguguofterdfyulioluktydfyiuofdtrsdfuliguydsrtfuftrsesj

