spring:
  application:
    name: authentification
#  data:
#    jdbc:
#      dialect: h2
  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  cloud:
    consul:
      discovery:
        register: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_base_td6_auth:3306/basetd6auth
    username: usertd6
    password: passwordtd6
  rabbitmq:
    host: rabbitmq
    password: guest
    port: 5672
    username: guest
    exchange: user.exchange
    queue: user.queue
    subscribe_routingkey: user.subscribe.routingkey
    unsubscribe_routingkey: user.unsubscribe.routingkey



mySecretKey : MySuperSecretKeyForJWTsguguofterdfyulioluktydfyiuofdtrsdfuliguydsrtfuftrsesj

