POST http://localhost:8080/api/utilisateurs
Content-Type: application/json

{
  "email": "demo1@etu.univ-orleans.fr",
  "password" : "demo1",
  "nom": "Hamid",
  "prenom": "Sougouma"
}

> {%
    client.global.set("etudiant_url", response.headers.valueOf("Location"));
    client.global.set("etudiant_token", response.headers.valueOf("Authorization"));
    client.test("Request Executed Succesfully", function () {
        client.assert(response.status === 201, "Response Status is not 201")
    })
%}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "demo1@etu.univ-orleans.fr",
  "password" : "demo1"
}

> {%
    client.global.set("etudiant_url", response.headers.valueOf("Location"));
    client.global.set("etudiant_token", response.headers.valueOf("Authorization"));
    client.test("Request Executed Succesfully", function () {
        client.assert(response.status === 200, "Response Status is not 200")
    })
%}

### Get user by Id
GET http://localhost:8080/api/utilisateurs/1
Authorization: {{etudiant_token}}


### DELETE USER
DELETE http://localhost:8080/api/utilisateurs/1
Authorization: {{etudiant_token}}